#!/usr/bin/env python3
"""Direct ATS apply-plan preview via official candidate APIs (fill-only).

This module is the ToS-clean apply-planning path: instead of scraping or
driving a browser, it shows what a direct application through the ATS
vendor's own public application endpoints would look like — as a
dry-run preview only. It never submits anything. Every endpoint in the
registry below was verified on 2026-09-10 via official documentation
and/or live non-mutating probes.

VERIFICATION RESULTS (2026-09-10)
---------------------------------
* Ashby — UNVERIFIED (not usable). Official docs describe
  ``POST https://api.ashbyhq.com/applicationForm.submit`` with JSON or
  multipart bodies
  (https://developers.ashbyhq.com/docs/creating-a-custom-careers-page).
  Live probes — an empty JSON body, a well-formed JSON body, and the
  documented multipart variant, all against a nonexistent ``jobPostingId``
  so nothing could be created — each returned ``401 Unauthorized``. The
  endpoint is not usable anonymously.
* Lever — UNVERIFIED (not usable). Live probes against a real posting on
  the ``qonto`` board: ``POST /v0/postings/qonto/{id}/apply`` returned 404
  (``Cannot POST ...``); ``POST /v0/postings/qonto/{id}`` with no key and
  an empty body returned 403
  ``{"ok":false,"error":"You need an API key. Please contact
  support@lever.co for a key"}``. The POST API key is issued by a Lever
  employee (https://www.rubydoc.info/gems/lever_postings).
* Greenhouse — endpoint EXISTS but requires an employer-issued credential.
  Official docs
  (https://github.com/grnhse/greenhouse-api-docs/blob/HEAD/source/includes/job-board/_applications.md):
  ``POST https://boards-api.greenhouse.io/v1/boards/{board_token}/jobs/{id}``
  requires HTTP Basic Auth with a Job Board API key generated by the
  employer inside Greenhouse. A job seeker cannot obtain one, so
  Greenhouse remains browser-only.

Consequence: no verified anonymous submit endpoint exists for any board,
and this module performs NO network submission at all — ``apply_direct()``
always returns a dry-run preview (zero network calls). The ``_ENDPOINTS``
registry below documents the 2026-09-10 verification results (status,
reason, sources) as reference only; there is no submit path a status
flip could enable.

Only stdlib is used.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import compliance
from providers._common import decode_payload

BASE_DIR = Path(__file__).resolve().parent

# ---------------------------------------------------------------------------
# Verified-endpoint registry.
#
# status: "verified"   -> (no board holds this status) historically meant
#                        the endpoint was proven to accept anonymous
#                        candidate submissions. The submit path is deleted;
#                        no registry status can re-arm submission.
#         "unverified" -> documented or rumored, but live probes showed it
#                        is NOT usable anonymously.
#         "key_required" -> endpoint exists per official docs but needs an
#                        employer-issued credential a job seeker cannot get.
# ---------------------------------------------------------------------------

_ENDPOINTS: dict[str, dict[str, Any]] = {
    "ashby": {
        "status": "unverified",
        "endpoint": "https://api.ashbyhq.com/applicationForm.submit",
        "method": "POST",
        "reason": (
            "Documented by Ashby, but live probes (empty JSON, structured "
            "JSON, and the documented multipart variant — all against a "
            "nonexistent jobPostingId, so non-mutating) returned 401 "
            "Unauthorized. Not usable anonymously."
        ),
        "sources": [
            "https://developers.ashbyhq.com/docs/creating-a-custom-careers-page",
        ],
    },
    "lever": {
        "status": "unverified",
        "endpoint": "https://api.lever.co/v0/postings/{site}/{posting_id}",
        "method": "POST",
        "reason": (
            "Live probe: POST without a key -> 403 "
            "'You need an API key. Please contact support@lever.co for a "
            "key'; the /apply path 404s. The POST API key is issued by a "
            "Lever employee."
        ),
        "sources": [
            "https://www.rubydoc.info/gems/lever_postings",
        ],
    },
    "greenhouse": {
        "status": "key_required",
        "endpoint": (
            "https://boards-api.greenhouse.io/v1/boards/"
            "{board_token}/jobs/{id}"
        ),
        "method": "POST",
        "reason": (
            "Endpoint exists per official docs, but requires HTTP Basic "
            "Auth with an employer-issued Job Board API key, which a job "
            "seeker cannot obtain. Browser-only."
        ),
        "sources": [
            "https://github.com/grnhse/greenhouse-api-docs/blob/HEAD/"
            "source/includes/job-board/_applications.md",
        ],
    },
}


def endpoint_status(board: str) -> dict[str, Any]:
    """Return the registry entry for a board (status, reason, sources)."""
    spec = _ENDPOINTS.get((board or "").strip().lower())
    if spec is None:
        return {"status": "unknown", "reason": "Board not in the registry.",
                "sources": []}
    return {
        "status": spec["status"],
        "endpoint": spec["endpoint"],
        "reason": spec["reason"],
        "sources": list(spec["sources"]),
    }


def describe_apply_path(board: str) -> dict[str, Any]:
    """Honest apply-path declaration for UI display (Initiative 09, epic 2).

    This is the "deepening" the official interfaces permit: where direct
    submission is impossible, the connector declares the limitation and
    names the supported path. The declaration itself is the feature —
    the user sees *why* before they hit the wall.
    """
    board = (board or "").strip().lower()
    status = endpoint_status(board)
    return {
        "board": board,
        "direct_apply_available": False,
        "endpoint_status": status["status"],
        "reason": status["reason"],
        "sources": status["sources"],
        "recommended_path": (
            "browser-assisted apply (apply_to_job): the ATS vendor's "
            "official interfaces do not permit anonymous direct "
            "submission, so Veto fills the employer's form in a "
            "browser you control and you confirm every submit."
        ),
        "official_interface_only": True,
    }


def _decode_locator(job_id: str) -> str:
    """Decode the locator payload from a self-describing job id.

    Job ids look like ``<board>:<base64url(payload)>`` (see
    providers._common.make_job_id). Raises ValueError when malformed.
    """
    _board, sep, token = str(job_id).partition(":")
    if not sep or not token:
        raise ValueError(f"Malformed job_id: {job_id!r}")
    return decode_payload(token)


def _preview_fields(
    applicant: dict[str, Any],
    cover_letter: str,
    resume_path: str | None,
) -> dict[str, Any]:
    """Field names/values that would be sent — never resume bytes."""
    fields: dict[str, Any] = {
        "full_name": applicant.get("full_name", ""),
        "email": applicant.get("email", ""),
        "phone": applicant.get("phone", ""),
        "location": applicant.get("location", ""),
        "linkedin_url": applicant.get("linkedin_url", ""),
        "website": applicant.get("website", ""),
        "cover_letter": f"<{len(cover_letter or '')} chars — text omitted>",
    }
    if resume_path:
        path = Path(resume_path).expanduser()
        fields["resume"] = (
            f"{path.name} (found, {path.stat().st_size} bytes — "
            "bytes never included in previews)"
            if path.is_file()
            else f"{path.name} (NOT FOUND)"
        )
    else:
        fields["resume"] = None
    return fields


def _preview(
    board: str,
    spec: dict[str, Any],
    job_id: str,
    locator: str,
    applicant: dict[str, Any],
    resume_path: str | None,
    cover_letter: str,
) -> dict[str, Any]:
    """Dry-run preview. Makes ZERO network calls."""
    preview: dict[str, Any] = {
        "mode": "preview",
        "dry_run": True,
        "network_calls": 0,
        "direct_apply_available": False,
        "board": board,
        "endpoint": spec["endpoint"],
        "endpoint_status": spec["status"],
        "status_reason": spec["reason"],
        "sources": list(spec["sources"]),
        "job_id": job_id,
        "locator": locator,
        "fields_for_manual_form": _preview_fields(
            applicant, cover_letter, resume_path
        ),
        "disclosure": compliance.apply_disclosure(board),
    }
    preview["note"] = (
        "No verified anonymous submit endpoint exists for this board; "
        "use the browser apply flow (apply_to_job) instead."
    )
    return preview


def apply_direct(
    board: str,
    job: dict[str, Any],
    applicant: dict[str, Any],
    resume_path: str | None = None,
    cover_letter: str = "",
    confirm: bool = False,
    dry_run: bool = True,
) -> dict[str, Any]:
    """Apply-plan preview via the official ATS API — preview only, never submits.

    ``job`` is a job dict from search (uses its ``id`` to decode the
    board-specific locator). ``applicant`` carries profile fields
    (full_name, email, phone, location, linkedin_url, website).

    Always returns a dry-run preview and makes ZERO network calls.
    ``confirm`` and ``dry_run`` are accepted for signature compatibility
    and do nothing: there is no submit path in this module.

    Raises:
        ValueError: If the board is not in the endpoint registry.
    """
    board = (board or "").strip().lower()
    spec = _ENDPOINTS.get(board)
    if spec is None:
        raise ValueError(
            f"Unknown board {board!r}; registry knows: {sorted(_ENDPOINTS)}"
        )
    job = job or {}
    applicant = applicant or {}
    job_id = str(job.get("id", ""))
    try:
        locator = _decode_locator(job_id)
    except ValueError as exc:
        return {"ok": False, "board": board, "error": str(exc)}

    return _preview(board, spec, job_id, locator, applicant,
                    resume_path, cover_letter)


# ---------------------------------------------------------------------------
# Wiring contract: the parent agent wires these into server.py / cli.py
# (this module never imports server.py at module level).
# ---------------------------------------------------------------------------


def register_tools(mcp: Any) -> Any:
    """Register the ``apply_via_ats`` MCP tool on a FastMCP instance."""

    @mcp.tool()
    def apply_via_ats(job_id: str, confirm: bool = False) -> dict[str, Any]:
        """Preview a direct-ATS application plan (preview only — never submits).

        Fill-only: this tool shows the field mapping and the endpoint
        status for the board's official candidate-submission endpoint —
        never scraping, never browser automation, and never a network
        submit. As of the last verification pass (2026-09-10) no board
        exposes a usable anonymous submit endpoint (Ashby 401s, Lever
        requires a Lever-issued API key, Greenhouse requires an
        employer-issued Job Board API key), and this module contains no
        submit path at all.

        Args:
            job_id: The job id returned by search_jobs (e.g. "ashby:...").
            confirm: Accepted for signature compatibility; does nothing.
                The tool always returns the dry-run preview.

        Returns:
            Dry-run preview dict (zero network calls): mode, board,
            endpoint, endpoint_status, fields_for_manual_form,
            disclosure, note.
        """
        # Lazy import: server.py owns the MCP app; importing it here would
        # be circular at module load time.
        from server import _load_saved_profile

        profile = _load_saved_profile()
        resume_default = BASE_DIR / "profiles" / "resume.pdf"
        resume_path = str(resume_default) if resume_default.is_file() else None
        board = str(job_id).partition(":")[0].strip().lower()
        return apply_direct(
            board,
            {"id": job_id, "board": board},
            profile,
            resume_path=resume_path,
            cover_letter=profile.get("cover_letter", ""),
        )

    return apply_via_ats


def _cli_apply_direct(args: Any) -> int:
    """Handler for ``cli.py apply-direct``. Returns a process exit code."""
    import json as _json

    from server import _decode_job_id, _load_saved_profile  # lazy

    profile = _load_saved_profile()
    try:
        board, _url = _decode_job_id(args.job_id)
    except ValueError as exc:
        print(_json.dumps({"ok": False, "error": str(exc)}, indent=2))
        return 1
    resume_default = BASE_DIR / "profiles" / "resume.pdf"
    resume_path = str(resume_default) if resume_default.is_file() else None
    result = apply_direct(
        board,
        {"id": args.job_id, "board": board},
        profile,
        resume_path=resume_path,
        cover_letter=profile.get("cover_letter", ""),
    )
    print(_json.dumps(result, indent=2, ensure_ascii=False))
    return 0


def register_cli(subparsers: Any) -> dict[str, Any]:
    """Add the ``apply-direct`` command to an argparse subparsers object.

    Adds ``--job-id`` (required). The command prints the dry-run apply
    preview (zero network calls); it never submits. Returns a
    {command: handler} mapping the caller merges into its own dispatch
    table, e.g.::

        handlers.update(ats_apply.register_cli(sub))

    The parser also gets ``func`` set so a caller can dispatch
    ``args.func(args)``.
    """
    parser = subparsers.add_parser(
        "apply-direct",
        help="Print the direct-ATS apply preview (never submits).",
    )
    parser.add_argument(
        "--job-id",
        required=True,
        help="Job id from the search output (e.g. 'ashby:...').",
    )
    parser.set_defaults(func=_cli_apply_direct)
    return {"apply-direct": _cli_apply_direct}
