#!/usr/bin/env python3
"""Release channels for Veto (Epic 6): stable, preview, migration notes,
and automated compatibility checks.

Channel manifests live in ``initiatives/i10/channels/``:

* ``stable.json`` / ``preview.json`` — ``{"version", "released_at",
  "schema_versions", "min_compatible", "notes"}``.
* ``notes/`` — human-readable migration notes per version, generated by
  :func:`migration_notes`.

Automated compatibility checks (run before any upgrade or channel
promotion):

1. Every stable-schema file in the data dir validates
   (``schemas.check_data_dir``).
2. Every applied migration's ``verify`` passes (``schema_migrate``).
3. The target channel's required schema versions are satisfied by the
   pending/applied migration chain (dry-run ``migrate`` proves the path
   exists).

``promote_preview_to_stable`` copies the preview manifest to stable only
when all checks pass on a release-candidate data directory.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from dataclasses import dataclass
from pathlib import Path

from . import schema_migrate, schemas

CHANNELS_DIR = Path(__file__).resolve().parent / "channels"
STABLE = "stable"
PREVIEW = "preview"


# ---------------------------------------------------------------------------
# Channel manifests
# ---------------------------------------------------------------------------


def _manifest_path(channel: str) -> Path:
    if channel not in (STABLE, PREVIEW):
        raise ValueError(f"Unknown channel {channel!r}; want stable|preview")
    return CHANNELS_DIR / f"{channel}.json"


def read_channel(channel: str) -> dict:
    path = _manifest_path(channel)
    if not path.exists():
        return {"channel": channel, "version": "0.0.0", "released_at": None}
    return json.loads(path.read_text(encoding="utf-8"))


def write_channel(channel: str, manifest: dict) -> Path:
    CHANNELS_DIR.mkdir(parents=True, exist_ok=True)
    path = _manifest_path(channel)
    path.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return path


def current_versions() -> dict[str, dict]:
    return {c: read_channel(c) for c in (STABLE, PREVIEW)}


# ---------------------------------------------------------------------------
# Migration notes
# ---------------------------------------------------------------------------


def migration_notes(from_version: str, to_version: str, data_dir: str | Path | None = None) -> str:
    """Generate migration notes between two package versions: which schema
    versions change, which migrations run, and what the user should do
    (backup first)."""
    lines = [
        f"# Veto migration notes: {from_version} → {to_version}",
        "",
        f"Generated {time.strftime('%Y-%m-%d')}. Back up before upgrading:",
        "  `python3 -m initiatives.i10.backup create --data-dir <dir> --out backup.vetobackup`",
        "",
        "## Schema versions",
        "",
    ]
    for name, ver in schemas.schema_versions().items():
        lines.append(f"- `{name}`: `{ver}`")
    lines += ["", "## Migrations that will run", ""]
    pending = schema_migrate.discover_migrations()
    if not pending:
        lines.append("None — no migrations registered.")
    for mig in pending:
        lines.append(f"### {mig.migration_id}")
        lines.append(f"- From: `{mig.from_version}` → To: `{mig.to_version}`")
    if data_dir is not None:
        lines += ["", "## Pre-upgrade compatibility check", ""]
        results = check_compatibility(Path(data_dir))
        for r in results:
            mark = "✓" if r["ok"] else "✗"
            lines.append(f"- [{mark}] {r['name']}: {r['detail']}")
    lines += [
        "",
        "## Rollback",
        "",
        "Every migration records a journal entry; roll back with:",
        "  `python3 -m initiatives.i10.schema_migrate rollback <migration_id> --data-dir <dir>`",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Automated compatibility checks
# ---------------------------------------------------------------------------


@dataclass
class CompatCheck:
    name: str
    ok: bool
    detail: str


def check_compatibility(data_dir: str | Path) -> list[CompatCheck]:
    """Automated compatibility checks over a data directory. All must pass
    before an upgrade or a preview→stable promotion."""
    data_dir = Path(data_dir)
    results: list[CompatCheck] = []

    # 1. Stable-schema validation.
    schema_results = schemas.check_data_dir(data_dir)
    if not schema_results:
        results.append(CompatCheck("schema-validation", True, "no stable-schema files present"))
    for r in schema_results:
        results.append(
            CompatCheck(
                f"schema-validation:{r.schema}",
                r.ok,
                f"{r.checked} checked, {r.invalid} invalid"
                + (f"; e.g. {r.problems[0]}" if r.problems else ""),
            )
        )

    # 2. Migration verify suite.
    runner = schema_migrate.MigrationRunner(data_dir)
    try:
        verify_results = runner.check_all()
    except Exception as exc:  # noqa: BLE001 — report, don't crash the gate
        verify_results = []
        results.append(CompatCheck("migration-verify", False, f"runner error: {exc}"))
    for r in verify_results:
        results.append(
            CompatCheck(f"migration-verify:{r['migration_id']}", r["ok"], str(r["verify"]))
        )
    if not verify_results and not any(c.name == "migration-verify" for c in results):
        results.append(CompatCheck("migration-verify", True, "no migrations applied yet"))

    # 3. Upgrade path exists (dry-run the pending chain).
    try:
        dry = runner.migrate(dry_run=True)
        results.append(
            CompatCheck(
                "upgrade-path",
                True,
                f"{len(dry)} pending migration(s) dry-run clean",
            )
        )
    except Exception as exc:  # noqa: BLE001
        results.append(CompatCheck("upgrade-path", False, f"dry-run failed: {exc}"))

    return results


def compatibility_ok(results: list[CompatCheck]) -> bool:
    return all(r.ok for r in results)


# ---------------------------------------------------------------------------
# Promotion
# ---------------------------------------------------------------------------


def promote_preview_to_stable(data_dir: str | Path, *, notes: str = "") -> dict:
    """Promote the preview manifest to stable. Requires every automated
    compatibility check to pass on the given release-candidate data dir."""
    results = check_compatibility(data_dir)
    if not compatibility_ok(results):
        failed = [r.name for r in results if not r.ok]
        raise RuntimeError(f"Promotion blocked: failing checks: {failed}")
    preview = read_channel(PREVIEW)
    stable_manifest = {
        "channel": STABLE,
        "version": preview.get("version"),
        "released_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
        "promoted_from": PREVIEW,
        "schema_versions": preview.get("schema_versions", schemas.schema_versions()),
        "notes": notes or preview.get("notes", ""),
    }
    write_channel(STABLE, stable_manifest)
    return {"promoted": preview.get("version"), "checks": len(results)}


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="veto-channels", description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("versions", help="Show channel versions")
    p = sub.add_parser("notes", help="Generate migration notes")
    p.add_argument("--from", dest="from_version", required=True)
    p.add_argument("--to", dest="to_version", required=True)
    p.add_argument("--data-dir", default="")
    p = sub.add_parser("check", help="Run automated compatibility checks")
    p.add_argument("--data-dir", required=True)
    p = sub.add_parser("promote", help="Promote preview → stable (gated)")
    p.add_argument("--data-dir", required=True)
    p.add_argument("--notes", default="")

    args = parser.parse_args(argv)
    if args.command == "versions":
        print(json.dumps(current_versions(), indent=2))
    elif args.command == "notes":
        print(
            migration_notes(
                args.from_version, args.to_version, args.data_dir or None
            ),
            end="",
        )
    elif args.command == "check":
        results = check_compatibility(args.data_dir)
        for r in results:
            mark = "✓" if r.ok else "✗"
            print(f"  [{mark}] {r.name}: {r.detail}")
        return 0 if compatibility_ok(results) else 1
    elif args.command == "promote":
        try:
            print(json.dumps(promote_preview_to_stable(args.data_dir, notes=args.notes), indent=2))
        except RuntimeError as exc:
            print(f"Blocked: {exc}")
            return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
