/* GENERATED by `python -m initiatives.i10.pwa stamp` — do not edit.
   Bundle content hash; the service worker derives CACHE_NAME from it.
   Re-stamp after ANY change under pwa/ or CI fails the sw-version-fresh check. */
self.VETO_SW_VERSION="fa93b0e4eea46172";
